server:
    port: 8888

spring:
    application:
        name: mssc-brewery-config
    cloud:
        config:
            server:
                git:
#                    authentication is not needed because repo is public
                    uri: https://github.com/andriewski/config-repo
                    clone-on-start: true
                    search-paths: '{application}'
    security:
      user:
          name: MyUserName
          password: MySuperSecretPassword

logging.level:
    org.springframework.cloud: debug
    org.springframework.web: debug
